### ISSUE TITLE
Добавить возможность кастомной обработки HTTP кодов для каждого метода

### ISSUE THREAD

**Issue by petropavel13** [TouchInstinct/LeadKit#180]
Зачастую, стороннее API возвращает вместо стандартной модели ответа некую модель с не 200 HTTP кодом. Хотелось бы иметь возможность добавить допустимые HTTP коды для конкретного метода (например, в виде доп. параметра в методе).
И ещё нужно подумать насчёт добавления этой фичи в api generator (создать issue с предлагаемым решением и обсудить).

**Comment by ZharaOo** [comment]
Готово
