### ISSUE TITLE
Добавить кастомизируемую кнопку

### ISSUE THREAD

**Issue by ArturAzarau** [TouchInstinct/LeadKit#184]
Должны присутствовать следующие возможности:
- Состояния: все от `UIControl.State` + состояние загрузки
- Кастомизация: 

1. Шрифт
2. `title`ы на все состояния
3. `attributedTitle`ы на все состояния
4. `titleCoor`ы на все состояния
5. Изображения на все состояния
6. `backgroundColor` на все состояния
7. Скруглённые углы
8. Инсеты для самой кнопки
- Добавление тени
- Тап по задизейбленной кнопке

**Comment by petropavel13** [comment]
done
