### ISSUE TITLE
Создание и разворачивание проекта скриптом

### ISSUE THREAD

**Issue by NikAshanin** [TouchInstinct/LeadKit#67]
Посмотреть и оценить возможность создания проекта с нуля со всей необходимой стартовой функциональностью путём запуска скрипта.
Всё что есть в документе "create_new_ios_project" должно быть в этом скрипте.

**Comment by petropavel13** [comment]
https://github.com/petropavel13/project-template-ios
Кроме "Настройка shared scheme в проекте" вроде всё работает более-менее
![gen_project](https://cloud.githubusercontent.com/assets/6436245/26116019/682ace5c-3a6a-11e7-9dd8-4ca8e06d13a9.gif)
